name: Dogfood
on: push

jobs:
  validate_links:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Run the private action
      uses: Youssef1313/markdown-links-verifier@v0.0.1
